### ISSUE TITLE
Missing backward compability

### ISSUE THREAD

**Issue by HeikoAdams** [MikeGriffinReborn/EntitySpaces#7]
Hello,
I'm currently porting our application to the current version of entity spaces and running in some problems:

- The Sort string-property of collections seems to be missing
- The Filter property was of type string but now it's an IQueryable
- The HasData property seems to be missing (I've replaced it with "== default" or "!= default")
- The AddNew Method is gone. How to replace it?
- The QueryReset Method is gone. How to replace it?

**These are showstopper for us!**

**Comment by MikeGriffinReborn** [comment]
Let me see if I can address these ...

### Filter
Let's start with Filter, it is still fully supported, here's an example. 
The key is you need to have a using statement for **System.Linq**

```c#
EmployeesCollection coll = new EmployeesCollection();
if (coll.LoadAll())
{
    // Filter on FirstName containing an "a"
    coll.Filter = coll.AsQueryable().Where(d => d.FirstName.Contains("a"));

    foreach (Employees employee in coll)
    {
        // Each employee's FirstName has an 'a' in
    }

    // Clear the filter
    coll.Filter = null;

    foreach (Employees employee in coll)
    {
        // All employees are now back in the list
    }
}
```

### HasData
This should still be present, is this what you are looking for?

```c#
Employees emp = new Employees();
if(emp.es.HasData)
{

}
```

### AddNew
This should also still work fine ...

```c#
EmployeesCollection coll = new EmployeesCollection();
Employees emp = coll.AddNew();
```

### QueryReset
That method is gone, it is recommended that you just new another Query object. To be honest, it's faster to create a new one rather than us trying to clean-up all the internal objects created in a query in order to reuse it.

### Sort
I looked for that, even in the old EntitySpaces source posted up there, I don't see it.  It is recommended that you use Filter for that, see ..

```c#
// Sorting by the Employee’s first name
coll.Filter = coll.AsQueryable().OrderByDescending(d => d.FirstName);

// Filtering for all Empoyees missing their FirstName
coll.Filter = coll.AsQueryable().Where(d => d.FirstName == null);

// Both Filtering and Sorting
coll.Filter = coll.AsQueryable().Where(d => d.FirstName == null).OrderByDescending(d => d.LastName);
```

I hope this answers most of your questions, feel free to ask away if not ...

**Comment by HeikoAdams** [comment]
Hi,
thanks for your answer. QueryReset has been remove from my code and using **.es.HasData** did the job for HasData - previously it was just **.HasData**

Am I right that I've to find a way to convert my string filter- and sort-expressions to linq to solve that issue?

**Comment by MikeGriffinReborn** [comment]
Ya, sorry on the Filter thing. It does offer a lot more power now though because you can do basically anything through the LINQ syntax to sort or filter a collection after it's loaded.

**Comment by HeikoAdams** [comment]
Marking the old filter- and sort-property obsolete would have been a better way. But now its as it is. ¯\_(ツ)_/¯
